country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="SoarRouterCool"
    psk="soar2526"
    priority=1
}

network={
    ssid="Boeing "
    psk="zzzzzzzz"
    priority=2
}


